Fix pyflakes errors commandinterface.py:36: 'linked' imported but unused commandinterface.py:43: 'readcsv' imported but unused commandinterface.py:277: redefinition of unused 'datasets' from line 38 datasets.py:30: 'plugins' imported but unused datasets.py:1530: redefinition of function '__getitem__' from line 1523 dbusinterface.py:154: redefinition of function 'ImportFileCSV' from line 144 dbusinterface.py:233: undefined name 'N' dbusinterface.py:249: redefinition of function 'SetToReference' from line 208 doc.py:152: local variable 'graph' is assigned to but never used doc.py:395: local variable 'ex' is assigned to but never used doc.py:715: local variable 'funcname' is assigned to but never used emf_export.py:26: 'sys' imported but unused linked.py:23: 'izip' imported but unused linked.py:28: 'simpleread' imported but unused linked.py:87: redefinition of function 'reloadLinks' from line 63 mime.py:191: local variable 'paths' is assigned to but never used operations.py:31: 'defaultdict' imported but unused operations.py:39: 'importparams' imported but unused operations.py:40: redefinition of unused 'datasets' from line 35 operations.py:1054: local variable 'data' is assigned to but never used operations.py:1434: local variable 'e' is assigned to but never used painthelper.py:24: 'utils' imported but unused readcsv.py:171: local variable 'v' is assigned to but never used svg_export.py:22: 'sys' imported but unused