Fix pyflakes warnings windows/mainwindow.py:117: local variable 'd' is assigned to but never used windows/plotwindow.py:23: 'izip' imported but unused windows/treeeditwindow.py:717: redefinition of unused 'widgets' from line 25