Use EnvironmentError rather than IOError. Move getting license to utils.
Fixes report:

Veusz version: 1.14
Python version: 2.7.1 (r271:86832, Nov 27 2010, 18:30:46) [MSC v.1500 32 bit (Intel)]
Python platform: win32
Numpy version: 1.5.1
Qt version: 4.7.2
PyQt version: 4.8.3
SIP version: 4.12.1
Date: Thu, 12 Jan 2012 17:28:22 +0000

Traceback (most recent call last):
  File "C:\src\veusz-msvc\veusz\build\pyi.win32\veusz_windows_pyinst\outPYZ1.pyz\veusz.windows.mainwindow", line 1215, in slotFileExport
  File "C:\src\veusz-msvc\veusz\build\pyi.win32\veusz_windows_pyinst\outPYZ1.pyz\veusz.document.export", line 94, in export
  File "C:\src\veusz-msvc\veusz\build\pyi.win32\veusz_windows_pyinst\outPYZ1.pyz\veusz.document.export", line 232, in exportPS
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: u'C:/Users/Kristel/Dropbox/Figure 1a and 1b.pdf'

What the user was doing before the crash
----------------------------------------
Exporting the file