Fix bug report for flashing qt object which has been deleted
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/veusz/windows/tutorial.py", line 845, in slotFlashTimeout
    self.flash.setStyleSheet('')
RuntimeError: wrapped C/C++ object of type QLabel has been deleted