Fix crash if missing argument in \size
Traceback (most recent call last):
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.windows.plotwindow", line 924, in checkPlotUpdate
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.document.doc", line 458, in paintTo
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.widgets.root", line 123, in draw
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.widgets.page", line 366, in draw
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.widgets.widget", line 309, in draw
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.widgets.textlabel", line 168, in draw
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.utils.textrender", line 1500, in Renderer
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.utils.textrender", line 1180, in __init__
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.utils.textrender", line 1313, in _initText
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.utils.textrender", line 1145, in makePartTree
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.utils.textrender", line 1145, in makePartTree
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.utils.textrender", line 1120, in makePartTree
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.utils.textrender", line 1140, in makePartTree
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.utils.textrender", line 901, in __init__
IndexError: list index out of range