Fix crash in boxplot with empty dataset:
Date: Tue, 01 Apr 2014 09:14:34 +0000

Traceback (most recent call last):
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.windows.plotwindow", line 904, in checkPlotUpdate
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.document.doc", line 424, in paintTo
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.widgets.root", line 123, in draw
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.widgets.page", line 335, in draw
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.widgets.page", line 273, in findAxisRanges
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.widgets.page", line 260, in processDepends
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.widgets.page", line 231, in processWidgetDeps
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.widgets.page", line 218, in _updateRangeFromPlotter
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.widgets.boxplot", line 293, in getRange
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\numpy.lib.nanfunctions", line 218, in nanmin
ValueError: zero-size array to reduction operation fmin which has no identity