Hopefully fix object deleted crash by moving to C++ style slot.
Error report:
Traceback (most recent call last):
  File "veusz/windows/treeeditwindow.pyc", line 1399, in settingMenu
  File "veusz/windows/treeeditwindow.pyc", line 1290, in updateHighlight
RuntimeError: wrapped C/C++ object of type QLabel has been deleted