Rewrite Line/FillSet control.
Previous code did not update if the setting was changed and did not
properly support extended fills.

Fixes report:

Veusz version: 1.22
Python version: 2.7.6 (v2.7.6:3a1db0d2747e, Nov 10 2013, 00:42:54)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
Python platform: darwin
Numpy version: 1.7.0
Qt version: 4.8.5
PyQt version: 4.10.3
SIP version: 4.15.3
Date: Tue, 10 Mar 2015 07:00:00 +0000

Traceback (most recent call last):
  File "veusz/setting/controls.pyc", line 1260, in onColorClicked
IndexError: list index out of range