Only use finite values in histogram and do not crash with zero-length datasets
Veusz version: 1.22
Python version: 2.7.9 (default, Feb  9 2015, 09:27:13)
[GCC 4.9.2]
Python platform: linux2
Numpy version: 1.8.2
Qt version: 4.8.6
PyQt version: 4.11.3
SIP version: 4.16.6
Date: Wed, 04 Mar 2015 14:14:12 +0000

Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/veusz/qtwidgets/datasetbrowser.py", line 347, in refresh
    }[self.grouping]()
  File "/usr/lib64/python2.7/site-packages/veusz/qtwidgets/datasetbrowser.py", line 280, in makeGrpTreeFilename
    FilenameNode
  File "/usr/lib64/python2.7/site-packages/veusz/qtwidgets/datasetbrowser.py", line 260, in makeGrpTree
    child = DatasetNode(self.doc, name, colitems, None)
  File "/usr/lib64/python2.7/site-packages/veusz/qtwidgets/datasetbrowser.py", line 58, in __init__
    data.append( ds.userSize() )
  File "/usr/lib64/python2.7/site-packages/veusz/document/datasets.py", line 581, in userSize
    return str( self.data.shape[0] )
  File "/usr/lib64/python2.7/site-packages/veusz/document/dataset_histo.py", line 274, in <lambda>
    data = property(lambda self: self.getData()[0])
  File "/usr/lib64/python2.7/site-packages/veusz/document/dataset_histo.py", line 256, in getData
    self.datacache = self.generator.getBinVals()
  File "/usr/lib64/python2.7/site-packages/veusz/document/dataset_histo.py", line 147, in getBinVals
    binlocs = self.binLocations()
  File "/usr/lib64/python2.7/site-packages/veusz/document/dataset_histo.py", line 76, in binLocations
    minval = N.nanmin(data)
  File "/usr/lib64/python2.7/site-packages/numpy/lib/nanfunctions.py", line 218, in nanmin
    res = np.fmin.reduce(a, axis=axis, out=out, keepdims=keepdims)
ValueError: zero-size array to reduction operation fmin which has no identity