Sticking plaster over report Do, 05 Jan 2012 12:06:11 +0000 Wonder what the real cause is? Veusz version: 1.14 Python version: 2.6.5 (r265:79063, Apr 16 2010, 13:09:56) [GCC 4.4.3] Python platform: linux2 Numpy version: 1.3.0 Qt version: 4.6.2 PyQt version: 4.7.2 SIP version: 4.10.1 Date: Do, 05 Jan 2012 12:06:11 +0000
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/veusz/utils/treemodel.py", line 153, in parent
    parentitem = childitem.parent
AttributeError: 'NoneType' object has no attribute 'parent'

What the user was doing before the crash
----------------------------------------
I changed the name of a column in the Dataset