Use unsigned long for widget ids instead of signed long
Python's id() function returns memory addresses, which do not fit into
signed long on 32-bit systems.

In PyQt 5.12 overflow checking is enabled by default, so this causes
errors like this:

Traceback (most recent call last):
  [...]
  File "/usr/lib/python3/dist-packages/veusz/widgets/graph3d.py", line 246, in drawToObject
    cont.assignWidgetId(id(self))
OverflowError: argument 1 overflowed: value must be in the range -2147483648 to 2147483647